### PR TITLE
CAW21-106 Created side by side sweetener list with filter on the left

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Created side by side list of sweeteners with the filter on the lft.

# Need Review By (Date)
- soon

# Urgency
- medium

# Steps to Test
1. in the stack root directory run `composer require su-sws/caw_profile:dev-CAW21-106 --no-update; composer update -n`
2. `blt drupal:sync --site=cardinalatwork`
3. create a basic page, and add a list paragraph to a One Column layout. Choose "Sweeteners" and "Side by Side" display for the list paragraph
4. Set the page layout as "Full Width"
5. View the page in all break points and ensure it looks ok.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@pookmish I got a little behind on my PRs and started to do this one. I see it has a conflicting file now?

**Comment by pookmish** [comment]
> @pookmish I got a little behind on my PRs and started to do this one. I see it has a conflicting file now?

@jenbreese luckily I was able to rebase the conflict out real easily.

**Comment by jenbreese** [comment]
> > @pookmish I got a little behind on my PRs and started to do this one. I see it has a conflicting file now?
> 
> @jenbreese luckily I was able to rebase the conflict out real easily.

Now some test errors? Can you rerun the tests?

**Comment by pookmish** [comment]
@jenbreese Tests are running through now.

**Comment by jenbreese** [comment]
@pookmish Can I tweak the css for the search and the button spacing?

**Comment by pookmish** [comment]
> @pookmish Can I tweak the css for the search and the button spacing?

@jenbreese absolutely. Have at it!

**Comment by jenbreese** [comment]
@pookmish I made some small changes in the css. If you like them, then I will approve and merge the pr.

**Review by jenbreese — APPROVED** [review]
GTG

**Pull request merged**
